#!/usr/bin/env python3
"""
render_reel.py - build a narrated image-sequence Reel from a JSON script.

Usage:
    python3 render_reel.py script.json -o reel.mp4

Expects, relative to the script file's folder:
    images/<beat image files>
    audio/<beat audio files>   (one file per beat, generated by your TTS step)

Beat durations are read from the audio files, so the video always stays in sync
with the voiceover. No manual timing needed.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

# ---------------------------------------------------------------- helpers


def run(cmd, **kw):
    """Run a command, raise with useful output on failure."""
    p = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if p.returncode != 0:
        sys.stderr.write("\n$ " + " ".join(str(c) for c in cmd) + "\n")
        sys.stderr.write(p.stderr[-4000:] + "\n")
        raise SystemExit(f"command failed ({p.returncode})")
    return p.stdout


def probe_duration(path):
    out = run([
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path),
    ])
    return float(out.strip())


def hex_to_ass(hex_color, alpha="00"):
    """#RRGGBB -> ASS &HAABBGGRR."""
    h = hex_color.lstrip("#")
    r, g, b = h[0:2], h[2:4], h[4:6]
    return f"&H{alpha}{b}{g}{r}".upper()


def ts(seconds):
    """Seconds -> ASS timestamp H:MM:SS.cc"""
    cs = int(round(seconds * 100))
    h, cs = divmod(cs, 360000)
    m, cs = divmod(cs, 6000)
    s, cs = divmod(cs, 100)
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


# ---------------------------------------------------------------- captions


def chunk_words(text, words_per_chunk):
    words = text.split()
    return [
        " ".join(words[i:i + words_per_chunk])
        for i in range(0, len(words), words_per_chunk)
    ] or [""]


def build_ass(beats, style, out_path):
    """
    Write a subtitle file. If a beat carries explicit `words`
    ([{"w":..,"start":..,"end":..}, ...] relative to the beat) those exact
    timings are used. Otherwise the beat text is split into short chunks and
    spread evenly across the beat -- close enough to feel synced.
    """
    W, H = style["width"], style["height"]
    primary = hex_to_ass(style["caption_color"])
    outline = hex_to_ass(style["caption_outline"])
    back = hex_to_ass(style["caption_shadow"], alpha="60")

    header = f"""[Script Info]
ScriptType: v4.00+
PlayResX: {W}
PlayResY: {H}
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Cap,{style["caption_font"]},{style["caption_size"]},{primary},{primary},{outline},{back},-1,0,0,0,100,100,0,0,1,{style["caption_outline_w"]},0,2,90,90,{style["caption_margin_v"]},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    lines = []
    clock = 0.0
    for b in beats:
        dur = b["_duration"]
        if b.get("no_caption"):
            clock += dur
            continue

        if b.get("words"):
            for w in b["words"]:
                lines.append((clock + w["start"], clock + w["end"], w["w"]))
        else:
            chunks = chunk_words(b["text"], style["caption_words_per_chunk"])
            slice_len = dur / len(chunks)
            for i, c in enumerate(chunks):
                lines.append((clock + i * slice_len,
                              clock + (i + 1) * slice_len,
                              c))
        clock += dur

    body = "\n".join(
        f"Dialogue: 0,{ts(a)},{ts(b)},Cap,,0,0,0,,{t.upper() if style['caption_upper'] else t}"
        for a, b, t in lines
    )
    out_path.write_text(header + body + "\n", encoding="utf-8")


# ---------------------------------------------------------------- video


def build_segment(beat, idx, style, root, build):
    """Render one beat to a silent mp4 with a slow Ken Burns move."""
    W, H, FPS = style["width"], style["height"], style["fps"]
    dur = beat["_duration"]
    frames = max(2, int(round(dur * FPS)))
    seg = build / f"seg_{idx:03d}.mp4"

    img = root / beat["image"]
    if not img.exists():
        raise SystemExit(f"missing image for beat {idx}: {img}")

    # Fit the artwork into a safe box, sat on the paper-coloured canvas.
    box_w = int(W * style["image_box_w"])
    box_h = int(H * style["image_box_h"])
    top = int(H * style["image_top"])

    # Alternate the zoom direction so consecutive beats don't feel identical.
    zoom_in = (idx % 2 == 0)
    amp = style["zoom_amount"]
    if zoom_in:
        z = f"1+{amp}*on/{frames}"
    else:
        z = f"{1 + amp}-{amp}*on/{frames}"

    # Upscale before zoompan, otherwise the pan visibly stair-steps.
    ss = style["zoom_supersample"]

    vf = (
        f"scale={box_w}:{box_h}:force_original_aspect_ratio=decrease,"
        f"pad={W}:{H}:(ow-iw)/2:{top}:color={style['bg']},"
        f"scale={W*ss}:{H*ss}:flags=bicubic,"
        f"zoompan=z='{z}'"
        f":x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'"
        f":d={frames}:s={W}x{H}:fps={FPS},"
        f"setsar=1,format=yuv420p"
    )

    run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-loop", "1", "-i", str(img),
        "-t", f"{dur:.4f}",
        "-vf", vf,
        "-r", str(FPS),
        "-c:v", "libx264", "-preset", "medium", "-crf", "18",
        str(seg),
    ])
    return seg


# ---------------------------------------------------------------- main


DEFAULT_STYLE = {
    "width": 1080,
    "height": 1920,
    "fps": 30,
    "bg": "#F2EDE4",

    "image_box_w": 0.92,      # artwork width as a fraction of the frame
    "image_box_h": 0.62,      # artwork height as a fraction of the frame
    "image_top": 0.13,        # where the artwork sits from the top

    "zoom_amount": 0.09,      # how much Ken Burns drift per beat
    "zoom_supersample": 2,    # raise to 3 for silkier motion, slower render

    "caption_font": "Poppins",
    "caption_size": 62,
    "caption_color": "#1A1A1A",
    "caption_outline": "#F2EDE4",
    "caption_outline_w": 4,
    "caption_shadow": "#000000",
    "caption_margin_v": 380,  # distance from the bottom edge
    "caption_words_per_chunk": 3,
    "caption_upper": True,

    "music_volume": 0.08,     # ducked under the voiceover
    "voice_volume": 1.0,
    "gap": 0.12,              # silence added after each beat, in seconds
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("script", help="path to script.json")
    ap.add_argument("-o", "--out", default="reel.mp4")
    ap.add_argument("--keep", action="store_true",
                    help="keep intermediate files in build/")
    args = ap.parse_args()

    for tool in ("ffmpeg", "ffprobe"):
        if not shutil.which(tool):
            raise SystemExit(f"{tool} not found on PATH")

    script_path = Path(args.script).resolve()
    root = script_path.parent
    data = json.loads(script_path.read_text(encoding="utf-8"))

    style = dict(DEFAULT_STYLE)
    style.update(data.get("style", {}))

    beats = data["beats"]
    if not beats:
        raise SystemExit("script has no beats")

    build = root / "build"
    build.mkdir(exist_ok=True)

    # --- 1. work out how long each beat runs, from its audio ------------
    print(f"reading {len(beats)} beats")
    for i, b in enumerate(beats):
        if b.get("audio"):
            ap_ = root / b["audio"]
            if not ap_.exists():
                raise SystemExit(f"missing audio for beat {i}: {ap_}")
            b["_duration"] = probe_duration(ap_) + style["gap"]
        elif b.get("duration"):
            b["_duration"] = float(b["duration"])
        else:
            raise SystemExit(f"beat {i} needs either `audio` or `duration`")

    total = sum(b["_duration"] for b in beats)
    print(f"total runtime {total:.2f}s")
    if total > 90:
        print("  ! over 90s - long for a Reel, consider cutting beats")

    # --- 2. one video segment per beat ---------------------------------
    segs = []
    for i, b in enumerate(beats):
        print(f"  beat {i+1}/{len(beats)}  {b['_duration']:.2f}s  "
              f"{textwrap.shorten(b.get('text',''), 46)}")
        segs.append(build_segment(b, i, style, root, build))

    # --- 3. stitch the video -------------------------------------------
    concat_v = build / "concat_v.txt"
    concat_v.write_text(
        "\n".join(f"file '{s.as_posix()}'" for s in segs) + "\n",
        encoding="utf-8")
    silent = build / "silent.mp4"
    run(["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0",
         "-i", str(concat_v), "-c", "copy", str(silent)])

    # --- 4. stitch the voiceover, padding each beat to its slot ---------
    voice = build / "voice.m4a"
    have_voice = any(b.get("audio") for b in beats)
    if have_voice:
        parts = []
        for i, b in enumerate(beats):
            part = build / f"vo_{i:03d}.m4a"
            if b.get("audio"):
                run(["ffmpeg", "-y", "-loglevel", "error",
                     "-i", str(root / b["audio"]),
                     "-af", f"apad=whole_dur={b['_duration']:.4f}",
                     "-ar", "48000", "-ac", "2", "-c:a", "aac", "-b:a", "192k",
                     str(part)])
            else:
                run(["ffmpeg", "-y", "-loglevel", "error",
                     "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo",
                     "-t", f"{b['_duration']:.4f}",
                     "-c:a", "aac", "-b:a", "192k", str(part)])
            parts.append(part)

        concat_a = build / "concat_a.txt"
        concat_a.write_text(
            "\n".join(f"file '{p.as_posix()}'" for p in parts) + "\n",
            encoding="utf-8")
        run(["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0",
             "-i", str(concat_a), "-c", "copy", str(voice)])

    # --- 5. captions ----------------------------------------------------
    ass = build / "captions.ass"
    build_ass(beats, style, ass)

    # --- 6. final mux ---------------------------------------------------
    out = Path(args.out)
    if not out.is_absolute():
        out = root / out

    cmd = ["ffmpeg", "-y", "-loglevel", "error", "-i", str(silent)]
    filters = [f"[0:v]ass='{ass.as_posix()}'[v]"]
    amix = []

    if have_voice:
        cmd += ["-i", str(voice)]
        amix.append(f"[{len(amix)+1}:a]volume={style['voice_volume']}[a0]")

    music = data.get("music")
    if music:
        cmd += ["-stream_loop", "-1", "-i", str(root / music)]
        idx = 2 if have_voice else 1
        amix.append(f"[{idx}:a]volume={style['music_volume']}[a1]")

    if len(amix) == 2:
        filters += amix + ["[a0][a1]amix=inputs=2:duration=first:"
                           "dropout_transition=0,dynaudnorm=p=0.85[a]"]
    elif len(amix) == 1:
        filters += amix + ["[a0]anull[a]"]

    cmd += ["-filter_complex", ";".join(filters), "-map", "[v]"]
    if amix:
        cmd += ["-map", "[a]", "-c:a", "aac", "-b:a", "192k"]
    cmd += ["-c:v", "libx264", "-preset", "medium", "-crf", "20",
            "-pix_fmt", "yuv420p", "-movflags", "+faststart",
            "-t", f"{total:.4f}", str(out)]

    run(cmd)

    if not args.keep:
        for f in build.glob("seg_*.mp4"):
            f.unlink()
        for f in build.glob("vo_*.m4a"):
            f.unlink()

    print(f"\ndone -> {out}  ({total:.1f}s, {style['width']}x{style['height']})")


if __name__ == "__main__":
    main()
